#!/usr/bin/env python3
"""Generate paper/fig_captions.tex from the figure sidecar JSONs.

Captions must not be written from memory. Every number, count and interval in a manuscript caption is
emitted here directly from the sidecar that the figure script wrote, so a caption cannot drift from
the figure it describes. manuscript.tex places the figures and calls these macros.

Run after any figure is rebuilt:
    python3 src/fig1b_tangent_vs_curve_residual.py
    python3 src/fig1c_nontriviality_q_baselines.py
    python3 src/fig2a_posterior_geometry_examples.py
    python3 src/build_manuscript_figures.py
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIG = os.path.join(ROOT, "figures")
OUT = os.path.join(ROOT, "paper", "fig_captions.tex")
CATS = ("GWTC-3", "O4a", "O4b")


def load(stem):
    p = os.path.join(FIG, f"{stem}.json")
    if not os.path.exists(p):
        raise SystemExit(f"FATAL: figure sidecar missing: {os.path.relpath(p, ROOT)}\n"
                         f"  Build it with:  python3 src/{stem.replace('fig1b_', 'fig1b_').replace('fig1c_', 'fig1c_')}.py")
    return json.load(open(p))


def main():
    b = load("fig1b_tangent_vs_curve_residual")
    c = load("fig1c_nontriviality_q_baselines")
    a = load("fig2a_posterior_geometry_examples")

    bt = ", ".join(f"{k} ($n={b['catalogs'][k]['n_elongated']}$): "
                   f"${b['catalogs'][k]['tangent']['median_deg']:.2f}^\\circ \\to "
                   f"{b['catalogs'][k]['curve']['median_deg']:.2f}^\\circ$" for k in CATS)
    ct = "; ".join(f"{k}: own-$q$ ${c['catalogs'][k]['own_q_deg']:.2f}^\\circ$ vs.\\ null minimum "
                   f"${c['catalogs'][k]['perm_null']['min']:.2f}^\\circ$" for k in CATS)
    def _panel(p):
        ev = p["event"].replace("_", r"\_")          # LaTeX-escape outside the f-string
        return (f"\\emph{{{p['panel']}}} {ev} ({p['catalog']}, axr ${p['axr']:.1f}$, "
                f"curve ${p['curve_err_deg']:.2f}^\\circ$, tangent ${p['tangent_err_deg']:.2f}^\\circ$)")
    ap = "; ".join(_panel(p) for p in a["panels"])
    tw = a["recorded_but_not_plotted"]

    _worst = next(p for p in a["panels"] if p["panel"].startswith("worst"))
    ts = _worst["tail_sensitivity"]["curve_err_range_deg"]
    tex = f"""% AUTO-GENERATED by src/build_manuscript_figures.py -- do not edit by hand.
% Every number below is read from a figure sidecar JSON, so captions cannot drift from the figures.
%
% Captions state what is plotted and the takeaway. Provenance, selection rules and methodological
% caveats belong in the text -- an external readability review flagged the earlier captions as
% mini-methods sections.

\\newcommand{{\\figonebcaption}}{{%
Reconstruction error against the local linear approximation, on elongated events
($\\mathrm{{axr}}\\ge{b['axr_min']:.0f}$) in three disjoint catalogs. Each thin line is one event, joining
its median-point tangent error to its constant-$\\mathcal{{M}}_c$ curve error; heavy bars are catalog
medians with a bootstrap interval over events. The curve improves on the tangent in every catalog:
{bt}. Note the logarithmic scale.}}

\\newcommand{{\\figoneccaption}}{{%
The reconstruction requires the \\emph{{event's own}} mass-ratio marginal. Blue circles use the event's own
$q$ marginal, orange squares the median-point tangent, grey diamonds a $q$ marginal pooled over the
catalog. The grey band spans the 5th--95th percentile of a permutation null in which each event is given a
different event's $q$ marginal ({c['catalogs']['GWTC-3']['perm_null']['n']} catalog-stratified draws); the
dark tick marks that null's minimum. Own-$q$ falls below the null minimum in every catalog ({ct}).}}

\\newcommand{{\\figtwoacaption}}{{%
Posterior geometry for three events chosen by fixed rules --- {ap}. Each panel shows the posterior
samples, the constant-$\\mathcal{{M}}_c$ curve, the measured principal axis and the two predicted
orientations, on equal-aspect axes. The worst case is included by rule rather than chosen, and carries a
zoom inset on its dense core; its failure is genuine, the error remaining at
${ts[0]:.1f}$--${ts[1]:.1f}^\\circ$ when the sample is trimmed to its central $90\\%$. Across all
elongated events the tangent beats the curve for
${tw['tangent_beats_curve_fraction_all_elongated']*100:.0f}\\%$ of events, rising to
${tw['tangent_beats_curve_fraction_axr_ge_8']*100:.0f}\\%$ above $\\mathrm{{axr}}=8$.}}
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(tex)
    print(f"wrote {os.path.relpath(OUT, ROOT)} from 3 sidecars")


if __name__ == "__main__":
    main()
