#!/usr/bin/env python3
"""Generate paper/fig_captions.tex from the figure sidecar JSONs.

Captions must not be written from memory. Every number, count and interval in a manuscript caption is
emitted here directly from the sidecar that the figure script wrote, so a caption cannot drift from
the figure it describes. manuscript.tex places the figures and calls these macros.

Run after any figure is rebuilt:
    python3 src/fig1b_tangent_vs_curve_residual.py
    python3 src/fig1c_nontriviality_q_baselines.py
    python3 src/fig2a_posterior_geometry_examples.py
    python3 src/build_manuscript_figures.py
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIG = os.path.join(ROOT, "figures")
OUT = os.path.join(ROOT, "paper", "fig_captions.tex")
CATS = ("GWTC-3", "O4a", "O4b")


def load(stem):
    p = os.path.join(FIG, f"{stem}.json")
    if not os.path.exists(p):
        raise SystemExit(f"FATAL: figure sidecar missing: {os.path.relpath(p, ROOT)}\n"
                         f"  Build it with:  python3 src/{stem.replace('fig1b_', 'fig1b_').replace('fig1c_', 'fig1c_')}.py")
    return json.load(open(p))


def main():
    b = load("fig1b_tangent_vs_curve_residual")
    c = load("fig1c_nontriviality_q_baselines")
    a = load("fig2a_posterior_geometry_examples")

    bt = ", ".join(f"{k} ($n={b['catalogs'][k]['n_elongated']}$): "
                   f"${b['catalogs'][k]['tangent']['median_deg']:.2f}^\\circ \\to "
                   f"{b['catalogs'][k]['curve']['median_deg']:.2f}^\\circ$" for k in CATS)
    ct = "; ".join(f"{k}: own-$q$ ${c['catalogs'][k]['own_q_deg']:.2f}^\\circ$ vs.\\ null minimum "
                   f"${c['catalogs'][k]['perm_null']['min']:.2f}^\\circ$" for k in CATS)
    def _panel(p):
        ev = p["event"].replace("_", r"\_")          # LaTeX-escape outside the f-string
        return (f"\\emph{{{p['panel']}}} {ev} ({p['catalog']}, axr ${p['axr']:.1f}$, "
                f"curve ${p['curve_err_deg']:.2f}^\\circ$, tangent ${p['tangent_err_deg']:.2f}^\\circ$)")
    ap = "; ".join(_panel(p) for p in a["panels"])
    tw = a["recorded_but_not_plotted"]

    _worst = next(p for p in a["panels"] if p["panel"].startswith("worst"))
    ts = _worst["tail_sensitivity"]["curve_err_range_deg"]
    tex = f"""% AUTO-GENERATED by src/build_manuscript_figures.py -- do not edit by hand.
% Every number below is read from a figure sidecar JSON, so captions cannot drift from the figures.

\\newcommand{{\\figonebcaption}}{{%
Reconstruction versus the local linear approximation, on elongated events
($\\mathrm{{axr}}\\ge{b['axr_min']:.0f}$) in three disjoint event catalogs. Each thin line is one event,
joining its median-point tangent error to its constant-$\\mathcal{{M}}_c$ curve reconstruction error;
heavy bars are catalog medians with a bootstrap interval computed over events. Medians:
{bt}. The vertical scale is logarithmic because per-event errors span roughly $0.01$--$24^\\circ$.
The interval is a bootstrap over the event sample, not the per-event Monte Carlo resolution of
Sec.~\\ref{{sec:residual}}.}}

\\newcommand{{\\figoneccaption}}{{%
The reconstruction requires the \\emph{{event's own}} mass-ratio marginal. For each catalog the blue
circle is the median error using the event's own $q$ marginal; the orange square is the median-point
tangent; the grey diamond substitutes a $q$ marginal pooled over the catalog. The grey band is a
\\textbf{{permutation null}}---the 5th--95th percentile of the catalog-median error when each event is
given a \\emph{{different}} event's $q$ marginal, over
{c['catalogs']['GWTC-3']['perm_null']['n']} catalog-stratified draws---and the dark tick marks that
null's \\emph{{minimum}}, i.e.\\ the single best of those draws. Own-$q$ lies below the null minimum in
every catalog ({ct}), so the permutation $p$-value is
$<1/{c['catalogs']['GWTC-3']['perm_null']['n']}$ in each. \\textbf{{The band is a null distribution: it
is not a confidence interval, not coverage, and not an uncertainty on own-$q$.}}}}

\\newcommand{{\\figtwoacaption}}{{%
\\textbf{{Illustrative examples}} of the posterior geometry and its reconstruction; this panel explains,
it does not establish a mechanism. Each panel shows one event's $(m_1,m_2)$ posterior samples, the
constant-$\\mathcal{{M}}_c$ curve through the event's median chirp mass, the measured principal axis, and
the two predicted orientations. Axes use \\emph{{equal aspect}}: orientation angles are only visually
truthful under equal aspect. Events are chosen by deterministic rules recorded in the figure sidecar,
not selected by eye: {ap}. The worst case is included by rule so the figure is not a gallery of
successes. Across all elongated events the tangent in fact beats the curve for
${tw['tangent_beats_curve_fraction_all_elongated']*100:.0f}\\%$ of events, rising to
${tw['tangent_beats_curve_fraction_axr_ge_8']*100:.0f}\\%$ above $\\mathrm{{axr}}=8$, where the curve's
advantage shrinks. No thickness-adjusted axis is drawn: finite posterior thickness is supported
out-of-sample but arc-varying thickness is \\emph{{not}} established (Sec.~\\ref{{sec:residual}}). The
worst-case panel is a heavy-tailed, high-mass posterior whose dense core occupies a small part of the
plotted range, so it carries a zoom inset on that core; the three directions there are the same lines,
not a re-fit. That failure is \\emph{{not}} an outlier artifact: trimming to the central $90\\%$ of samples
leaves the error at ${ts[0]:.1f}$--${ts[1]:.1f}^\\circ$, so the curve genuinely misses this event.}}
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(tex)
    print(f"wrote {os.path.relpath(OUT, ROOT)} from 3 sidecars")


if __name__ == "__main__":
    main()
